spring.application.name=rose

spring.datasource.url=jdbc:postgresql://localhost:5433/rose
spring.datasource.username=rose_user
spring.datasource.password=rose_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true